# Generated by Django 5.0.1 on 2024-01-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApi', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menu_item_id',
            new_name='menuitem_id',
        ),
    ]
