# Generated by Django 5.0.1 on 2024-01-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApi', '0003_rename_menu_item_id_rating_menuitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='raiting',
            new_name='rating',
        ),
    ]
